### ISSUE TITLE
Opacity is hardcoded

### ISSUE THREAD

**Issue by Lemmmy** [SidebarJS/sidebarjs#7]
Add an option to change the opacity? It's currently hardcoded to 0.3

**Comment by lorenzodianni** [comment]
Hi @Lemmmy, thanks for your feedback.

The intention of this library is to simulate the native sidebar/sidenav of mobile devices.
As you can see on mobile devices, the native sidebar/sidenav has a soft opacity on the backdrop, so i'd like to avoid options that may change the "native" style.

Anyway, if you want a different opacity, you can change it with a simple css override:
```css
[sidebarjs].sidebarjs--is-visible [sidebarjs-background] {
    opacity: 1;
}
```
